FROM docker.io/python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        zip \
        curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tests
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["sleep", "infinity"]
